const repos = [
  {
    id: 1,
    name: "聚宝盆100W",
    deliveryPrice: "14.48",
    sku: "TYNJBPBD1",
    description: "聚宝盆",
  },
  {
    id: 2,
    name: "聚宝盆200W",
    deliveryPrice: "19.44",
    sku: "TKTYNJBPBD2",
    description: "聚宝盆",
  },
  {
    id: 3,
    name: "聚宝盆400W",
    deliveryPrice: "30.04",
    sku: "TKTYNJBPBD3",
    description: "聚宝盆",
  },
  {
    id: 4,
    name: "聚宝盆600W",
    deliveryPrice: "39.99",
    sku: "TKTYNJBPBD4",
    description: "聚宝盆",
  },
  {
    id: 5,
    name: "太阳能五铢爆闪t投光灯（140珠）",
    deliveryPrice: "27.03",
    sku: "TKTYBS01",
    description: "太阳能五铢爆闪灯",
  },
  {
    id: 6,
    name: "太阳能五铢爆闪t投光灯（270珠）",
    deliveryPrice: "38.63",
    sku: "TKTYBS02",
    description: "太阳能五铢爆闪灯",
  },
  {
    id: 7,
    name: "太阳能五铢爆闪t投光灯（385珠）",
    deliveryPrice: "48.91",
    sku: "TKTYBS03",
    description: "太阳能五铢爆闪灯",
  },
  {
    id: 8,
    name: "太阳能方形吸顶灯（三色）128珠",
    deliveryPrice: "25.84",
    sku: "TKTYNFXD1",
    description: "太阳能方形吸顶灯",
  },
  {
    id: 9,
    name: "太阳能方形吸顶灯（三色）240珠",
    deliveryPrice: "40.38",
    sku: "TKTYNFXD2",
    description: "太阳能方形吸顶灯",
  },
  {
    id: 10,
    name: "太阳能方形吸顶灯（三色）308珠",
    deliveryPrice: "47.69",
    sku: "TKTYNFXD3",
    description: "太阳能方形吸顶灯",
  },
  {
    id: 11,
    name: "灯泡200W（5cm）",
    deliveryPrice: "15.65",
    sku: "TKTYNDP1",
    description: "灯泡",
  },
  {
    id: 12,
    name: "灯泡400W（8cm）",
    deliveryPrice: "19.77",
    sku: "TKTYNDP2",
    description: "灯泡",
  },
  {
    id: 13,
    name: "灯泡600W（10cm）",
    deliveryPrice: "21.45",
    sku: "TKTYNDP3",
    description: "灯泡",
  },
  {
    id: 14,
    name: "灯泡800W（12cm）",
    deliveryPrice: "24.15",
    sku: "TKTYNDP4",
    description: "灯泡",
  },
  {
    id: 15,
    name: "灯泡1000W（15cm）",
    deliveryPrice: "42.18",
    sku: "TKTYNDP5",
    description: "灯泡",
  },
  {
    id: 16,
    name: "满天星200W",
    deliveryPrice: "17.8",
    sku: "TKTYNBD1",
    description: "满天星",
  },
  {
    id: 17,
    name: "满天星400W",
    deliveryPrice: "24.3",
    sku: "TKTYNBD2",
    description: "满天星",
  },
  {
    id: 18,
    name: "满天星600W",
    deliveryPrice: "35.51",
    sku: "TKTYNBD3",
    description: "满天星",
  },
  {
    id: 19,
    name: "满天星800W",
    deliveryPrice: "57.2",
    sku: "TKTYNBD4",
    description: "满天星",
  },
  {
    id: 20,
    name: "梦之蓝300W",
    deliveryPrice: "23.15",
    sku: "TKTYNMZL1",
    description: "梦之蓝",
  },
  {
    id: 21,
    name: "梦之蓝500W",
    deliveryPrice: "35.18",
    sku: "TKTYNMZL2",
    description: "梦之蓝",
  },
  {
    id: 22,
    name: "梦之蓝1000W",
    deliveryPrice: "46.52",
    sku: "TKTYNMZL3",
    description: "梦之蓝",
  },
  {
    id: 23,
    name: "梦之蓝1500W",
    deliveryPrice: "64.49",
    sku: "TKTYNMZL4",
    description: "梦之蓝",
  },
  {
    id: 24,
    name: "UFO5格",
    deliveryPrice: "71.75",
    sku: "TGUFO1",
    description: "UFO",
  },
  {
    id: 25,
    name: "UFO9格",
    deliveryPrice: "80.79",
    sku: "TGUFO2",
    description: "UFO",
  },
  {
    id: 26,
    name: "太阳能月神飞碟灯",
    deliveryPrice: "114.69",
    sku: "TGUFO3",
    description: "太阳能月神",
  },
  {
    id: 27,
    name: "户外手提灯（4格）",
    deliveryPrice: "26.36",
    sku: "JZFZSTD01",
    description: "户外手提灯",
  },
  {
    id: 28,
    name: "户外手提灯（6格）",
    deliveryPrice: "32.13",
    sku: "JZFZSTD02",
    description: "户外手提灯",
  },
  {
    id: 29,
    name: "王者一体500W",
    deliveryPrice: "43.36",
    sku: "WGLD1",
    description: "王者一体",
  },
  {
    id: 30,
    name: "王者一体1000W",
    deliveryPrice: "54.56",
    sku: "WGLD2",
    description: "王者一体",
  },
  {
    id: 31,
    name: "王者一体1500W",
    deliveryPrice: "68.13",
    sku: "WGLD3",
    description: "王者一体",
  },
  {
    id: 32,
    name: "吸光灯200W",
    deliveryPrice: "17.54",
    sku: "TYNXDD1",
    description: "吸光灯",
  },
  {
    id: 33,
    name: "吸光灯300W",
    deliveryPrice: "23.89",
    sku: "TYNXDD2",
    description: "吸光灯",
  },
  {
    id: 34,
    name: "吸光灯500W",
    deliveryPrice: "38.37",
    sku: "TYNXDD3",
    description: "吸光灯",
  },
  {
    id: 35,
    name: "吸光灯1000W",
    deliveryPrice: "47.93",
    sku: "TYNXDD4",
    description: "吸光灯",
  },
  {
    id: 36,
    name: "牙刷款路灯1头",
    deliveryPrice: "32.3",
    sku: "JZDZLD01",
    description: "牙刷款路灯",
  },
  {
    id: 37,
    name: "牙刷款路灯2头",
    deliveryPrice: "70.56",
    sku: "JZDZLD02",
    description: "牙刷款路灯",
  },
  {
    id: 38,
    name: "牙刷款路灯4头",
    deliveryPrice: "81.46",
    sku: "JZDZLD03",
    description: "牙刷款路灯",
  },
  {
    id: 39,
    name: "牙刷款路灯6头",
    deliveryPrice: "86.58",
    sku: "JZDZLD04",
    description: "牙刷款路灯",
  },
  {
    id: 40,
    name: "延长线",
    deliveryPrice: "3.72",
    sku: "YCX5M",
    description: "延长线",
  },
  {
    id: 41,
    name: "园林剪",
    deliveryPrice: "15.51",
    sku: "YLJD",
    description: "园林剪",
  },
  {
    id: 42,
    name: "剥线剪-1",
    deliveryPrice: "9.66",
    sku: "BXJ1",
    description: "剥线剪",
  },
  {
    id: 43,
    name: "剥线剪-2",
    deliveryPrice: "11.17",
    sku: "BXJ2",
    description: "剥线剪",
  },
  {
    id: 44,
    name: "剥线剪-3",
    deliveryPrice: "11.13",
    sku: "BXJ3",
    description: "剥线剪",
  },
  {
    id: 45,
    name: "套筒扳手",
    deliveryPrice: "11.14",
    sku: "TTBSXF",
    description: "套筒扳手",
  },
  {
    id: 46,
    name: "台球杆",
    deliveryPrice: "75.88",
    sku: "TQG",
    description: "台球杆",
  },
  {
    id: 47,
    name: "净水器（1头+1芯）",
    deliveryPrice: "7.05",
    sku: "JSQ",
    description: "净水器",
  },
  {
    id: 48,
    name: "净水器滤芯",
    deliveryPrice: "2.69",
    sku: "JSQLX",
    description: "滤芯",
  },
  {
    id: 49,
    name: "净水器拧头",
    deliveryPrice: "3.09",
    sku: "JSQNT",
    description: "拧头",
  },
  {
    id: 50,
    name: "洗头刷",
    deliveryPrice: "3.7",
    sku: "XTS",
    description: "洗头刷",
  },
  {
    id: 51,
    name: "高背月亮椅（卡其）",
    deliveryPrice: "43.23",
    sku: "ZDYY",
    description: "高背月亮椅",
  },
  {
    id: 52,
    name: "高背月亮椅（黑色）",
    deliveryPrice: "43.23",
    sku: "ZDYB",
    description: "高背月亮椅",
  },
  {
    id: 53,
    name: "高背月亮椅（军绿色）",
    deliveryPrice: "43.23",
    sku: "ZDYG",
    description: "高背月亮椅",
  },
  {
    id: 54,
    name: "不锈钢保温杯粉色890ML",
    deliveryPrice: "21.85",
    sku: "BXGSBFS",
    description: "不锈钢保温杯",
  },
  {
    id: 55,
    name: "不锈钢保温杯白色890ML",
    deliveryPrice: "21.85",
    sku: "BXGSBBS",
    description: "不锈钢保温杯",
  },
  {
    id: 56,
    name: "不锈钢保温杯蓝色890ML",
    deliveryPrice: "21.85",
    sku: "BXGSBLS",
    description: "不锈钢保温杯",
  },
  {
    id: 57,
    name: "50cm面宽一层折香收纳柜(透明茶)",
    deliveryPrice: "33.2",
    sku: "50CWG01",
    description: "折香收纳柜",
  },
  {
    id: 58,
    name: "50cm面宽三层折香收纳柜(透明茶)",
    deliveryPrice: "68.53",
    sku: "50CWG03",
    description: "折香收纳柜",
  },
  {
    id: 59,
    name: "50cm面宽五层折香收纳柜(透明茶)",
    deliveryPrice: "102.74",
    sku: "50CWG05",
    description: "折香收纳柜",
  },
  {
    id: 60,
    name: "56cm面宽一层折香收纳柜(透明茶)",
    deliveryPrice: "38.03",
    sku: "56CWG01",
    description: "折香收纳柜",
  },
  {
    id: 61,
    name: "56cm面宽三层折香收纳柜(透明茶)",
    deliveryPrice: "86.2",
    sku: "56CWG03",
    description: "折香收纳柜",
  },
  {
    id: 62,
    name: "56cm面宽五层折香收纳柜(透明茶)",
    deliveryPrice: "133.77",
    sku: "56CWG05",
    description: "折香收纳柜",
  },
  {
    id: 63,
    name: "宠物蒸汽毛刷(白色)",
    deliveryPrice: "5.5",
    sku: "TKCWZQMSBS",
    description: "宠物蒸汽毛刷",
  },
  {
    id: 64,
    name: "宠物蒸汽毛刷(米色)",
    deliveryPrice: "5.5",
    sku: "TKCWZQMSMS",
    description: "宠物蒸汽毛刷",
  },
];
export function getRepos(params?: any) {
  // If no params are provided, return all repos
  if (params === undefined) {
    return {
      data: repos,
      success: true,
    };
  }

  // Create a copy of the repos array for filtering
  let filteredRepos = [...repos];

  // Filter by SKU if provided
  if (params.sku) {
    const skuRegex = new RegExp(params.sku, "i");
    filteredRepos = filteredRepos.filter((repo) => skuRegex.test(repo.sku));
  }

  // Filter by name if provided
  if (params.name) {
    const nameRegex = new RegExp(params.name, "i");
    filteredRepos = filteredRepos.filter((repo) => nameRegex.test(repo.name));
  }

  // Return the filtered repos
  return {
    data: filteredRepos,
    success: true,
  };
}
